opacity: 1.0
title: Alacritty

font:
  normal: 
    family: SauceCodePro Nerd Font Mono
    style: Medium
  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: SauceCodePro Nerd Font Mono
    style: Italic
  bold_italic:
    family: SauceCodePro Nerd Font Mono
    style: Bold Italic
  size: 18

window:
  padding:
    x: 15
    y: 15

# Colors (substrata)
colors:
  primary:
    background: '#1c1c1c'
    foreground: '#ffffff'
  normal:
    black:   '#000000'
    red:     '#FF3B30'
    green:   '#4CD964'
    yellow:  '#FFCC00'
    blue:    '#0095FF'
    magenta: '#927CCF'
    cyan:    '#5AC8FA'
    white:   '#FFFFFF'
  bright:
    black:   '#686868'
    red:     '#FF3B30'
    green:   '#4CD964'
    yellow:  '#FFCC00'
    blue:    '#0095FF'
    magenta: '#FF2D55'
    cyan:    '#5AC8FA'
    white:   '#FFFFFF'
