background: &background 002635ff
foreground: &foreground e6e6dcff
focus: &focus b7cff9ff

bar: 
  font: "Ubuntu:style=Bold:size=17" # 12
  location: top
  height: 23 # 19
  margin: 10
  spacing: 4
  background: *background
  foreground: *foreground

  right:
    - alsa: 
        card: default
        mixer: Capture
        content: 
          map:
            tag: muted
            values:
              false:
                string:
                  font: "Material:size=18"
                  text: "󰍬" 
                  foreground: *focus

    - clock:
        time-format: "%R"
        date-format: "%a %d %b"
        content: { string: { text: "{date}. {time}"}}

  center:
    - mpd: 
        host: localhost
        port: 6600
        content:
          map:
            tag: state
            values:
              playing:
                string: { text: "{artist} - {title}" }

  left:
    - river:
        anchors:
          - base: &river_base
              tag: occupied
              values:
                false: { empty: {}}
                true: 
                  string:
                    margin: 5
                    text: "{id}"
        content:
          map:
            tag: state
            values: 
              focused: 
                string:
                  text: "{id}"
                  margin: 5
                  foreground: *background
                  deco: { background: { color: *focus }}
              unfocused:
                map:
                  <<: *river_base
              visible:
                map:
                  <<: *river_base
              invisible:
                map:
                  <<: *river_base
