background: &background 1d2021ff
foreground: &foreground d5c4a1ff
focus: &focus fb4934ff

bar: 
  font: "Ubuntu:style=Bold:size=12"
  location: top
  height: 19
  margin: 5
  spacing: 4
  background: *background
  foreground: *foreground

  right:
    - alsa: 
        card: default
        mixer: Capture
        content: 
          map:
            tag: muted
            values:
              false:
                string:
                  font: "Material:size=13"
                  text: "󰍬" 
                  foreground: *focus

    - clock:
        time-format: "%R"
        date-format: "%a %d %b"
        content: { string: { text: "{date}. {time}"}}

  left:
    - river:
        anchors:
          - base: &river_base
              tag: occupied
              values:
                false: { empty: {}}
                true: 
                  string:
                    margin: 5
                    text: "{id}"
        content:
          map:
            tag: state
            values: 
              focused: 
                string:
                  text: "{id}"
                  margin: 5
                  foreground: *background
                  deco: { background: { color: *focus }}
              unfocused:
                map:
                  <<: *river_base
              visible:
                map:
                  <<: *river_base
              invisible:
                map:
                  <<: *river_base


