theme = "monokai_pro"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
# select = "underline"

[keys.normal]
# C-o = ":config-open"
C-r = ":config-reload"

# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
# "%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
# C = ["collapse_selection", "extend_to_line_end", "change_selection"]
D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable
C-e = "scroll_down"
C-y = "scroll_up"
A-j = "copy_selection_on_next_line"
A-k = "copy_selection_on_prev_line"
Z = { Z = ":wq", Q = ":q!" }

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
# "%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for
C-e = "scroll_down"
C-y = "scroll_up"
Z = { Z = ":wq", Q = ":q!" }

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"] 
